name: Crystal CI

on:
  push:
    paths:
      - 'crystal/**'
      - '.github/workflows/crystal**'
  pull_request:
    paths:
      - 'crystal/**'
      - '.github/workflows/crystal**'

  schedule:
    # weekly build every FRI
    - cron: "0 6 * * 5"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        crystal: ['1.14', '1.15', 'latest']
    runs-on: ${{ matrix.os }}

    name: Crystal ${{ matrix.crystal }} Build on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ matrix.crystal }}

    #### BEGIN crystal spectator
    - name: crystal spectator
      working-directory: crystal/spectator
      run: "shards install && sh ../../.scripts/assure_failing_test.sh 'crystal spec' '1) Kata greets the given name'"

    #### END crystal spectator
